<a href="https://colab.research.google.com/github/tekuugr-0205-16-hub/torch_tutorial/blob/main/pytorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch


!pip



Usage:   
  pip3 <command> [options]

Commands:
  install                     Install packages.
  download                    Download packages.
  uninstall                   Uninstall packages.
  freeze                      Output installed packages in requirements format.
  inspect                     Inspect the python environment.
  list                        List installed packages.
  show                        Show information about installed packages.
  check                       Verify installed packages have compatible dependencies.
  config                      Manage local and global configuration.
  search                      Search PyPI for packages.
  cache                       Inspect and manage pip's wheel cache.
  index                       Inspect information available from package indexes.
  wheel                       Build wheels from your requirements.
  hash                        Compute hashes of package archives.
  completion                  A helper c

let go for the tensor


In [2]:
import numpy as np

List


In [3]:
my_List = [1,4,5,6,4,6]
my_List

[1, 4, 5, 6, 4, 6]

numpy_array


In [4]:
np1 = np.random.rand(3,4)
np1

array([[0.12563895, 0.57175887, 0.59415054, 0.29528425],
       [0.20834649, 0.21211041, 0.76420179, 0.4109739 ],
       [0.2913072 , 0.59256814, 0.01500135, 0.80279563]])

In [5]:
np1.dtype

dtype('float64')

Tensor


In [6]:
tensor_2d= torch.randn(3,4)
tensor_2d


tensor([[-2.9645, -0.4676, -1.1268,  1.6625],
        [-0.3386,  0.0974,  0.8467, -0.4809],
        [-0.3889, -0.4444, -1.2275,  0.6921]])

In [7]:
tensor_2d.dtype

torch.float32

In [8]:
tensor_3d = torch.randn(2,3,4)
tensor_3d

tensor([[[-0.0790, -0.3440, -0.5350,  0.9093],
         [-0.7385, -0.8679,  0.9624,  0.4129],
         [-0.6114, -0.8408, -0.9412,  0.6281]],

        [[ 1.4514, -2.6184,  1.3132,  1.1252],
         [-1.5590,  0.1031, -0.2229, -0.8517],
         [ 1.5253, -0.4970,  0.3320, -0.7535]]])

In [9]:
teonsr_numpy= torch.from_numpy(np1)
teonsr_numpy
teonsr_numpy.dtype

torch.float64

reshape and slice an the tensor love buddy hmm let go guys togther

In [10]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
#let talk and the reshape and view
my_torch =my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
my_torch = my_torch.reshape(5,-1)
my_torch

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [13]:
my_torch =my_torch.view(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

the deffence between them is https://mr-amit.medium.com/pytorch-view-vs-reshape-a-practical-guide-74bf31eec210

In [14]:
my_torch0 = torch.arange(10)
my_torch0

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
my_torch1 = my_torch0.reshape(5,2)
my_torch1

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [16]:
my_torch[:,0]

tensor([0, 5])

In [17]:
my_torch1[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

Tensor math  operation

In [18]:
from torch import tensor


In [19]:
tensor_a = tensor([2,4,6,8])
tensor_b = tensor([1,3,5,7])
tensor_a+tensor_b

tensor([ 3,  7, 11, 15])

In [20]:
#addtion longhand
torch.add(tensor_a,tensor_b)
#

tensor([ 3,  7, 11, 15])

In [21]:
tensor_a-tensor_b

tensor([1, 1, 1, 1])

In [22]:
torch.sub(tensor_a,tensor_b)

tensor([1, 1, 1, 1])

In [23]:
tensor_a*tensor_b

tensor([ 2, 12, 30, 56])

In [24]:
torch.sub(tensor_a,tensor_b)

tensor([1, 1, 1, 1])

In [25]:
tensor_a/tensor_b

tensor([2.0000, 1.3333, 1.2000, 1.1429])

In [26]:
torch.div(tensor_a,tensor_b)

tensor([2.0000, 1.3333, 1.2000, 1.1429])

also the remander or the modules is work in the torch